[package]
name = "crabbyqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
directories = "6.0.0"
# gpui = "0.2.2"

gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit", "x11", "wayland", "runtime_shaders"] }
gpui-component = { version = "0.5.1", git = "https://github.com/longbridge/gpui-component.git", rev = "5b3c3ebcaf973168d54c6a66e3ccd1fa2d115926" }
gpui-component-assets = { version = "0.5.1", git = "https://github.com/longbridge/gpui-component.git", rev = "5b3c3ebcaf973168d54c6a66e3ccd1fa2d115926" }

lsp-types = "0.97.0"
rust-embed = "8.11.0"
rust-i18n = "3.1.5"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tree-sitter = "0.25.10"
tree-sitter-sequel = "0.3.11"

[dependencies.sqlx]
version = "0.8.6"
features = [ "runtime-tokio", "sqlite" ]

[dev-dependencies]
gpui-component = { version = "0.5.1", features = ["inspector"], git = "https://github.com/longbridge/gpui-component.git", rev = "5b3c3ebcaf973168d54c6a66e3ccd1fa2d115926" }


# Pin GPUI to a specific revision
[patch."https://github.com/zed-industries/zed"]
gpui = { git = "https://github.com/jacobtread/zed", rev = "4668aeb7284780cca830ba1173c4d3eb8bd11e2b" }
gpui_platform = { git = "https://github.com/jacobtread/zed", rev = "4668aeb7284780cca830ba1173c4d3eb8bd11e2b" }
